services:
  popfri:
    build: .
    ports:
      - "5173:5173"
    command: ["npm", "run", "preview"]
  matomo:
    image: matomo:latest
    ports:
      - "8080:80"
    volumes:
      - ./matomo/matomo-data:/var/www/html
      - ./nginx/container-js:/var/www/html/js-export 

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/container-js:/usr/share/nginx/html/js